spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
