spring:
  application:
    name: nuPrecin
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/nuprecin
    username: postgres
    password: Toloco
server:
  error:
    include-stacktrace: never
springdoc:
  swagger-ui:
    path: /swagger-ui.html